//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCSQLConnect.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCCSQLTest02\\ccctest4;Initial Catalog=Justice;Integrated Security=Tru" +
            "e;TrustServerCertificate=True")]
        public string JusticeTEST4 {
            get {
                return ((string)(this["JusticeTEST4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCCSQLTest02\\ccctest8;Initial Catalog=Justice;Integrated Security=Tru" +
            "e;TrustServerCertificate=True")]
        public string JusticeTEST8 {
            get {
                return ((string)(this["JusticeTEST8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CMSSQLPRDN03\\ILCOOKPROD;Initial Catalog=Justice;Integrated Security=T" +
            "rue;TrustServerCertificate=True")]
        public string JusticePROD {
            get {
                return ((string)(this["JusticePROD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCCSQLTest02\\ccctest4;Initial Catalog=Justice;User Id=EJuser;Password" +
            "=Fh80UXq363PHa4B;Integrated Security=True;TrustServerCertificate=True")]
        public string JusticeTST4U {
            get {
                return ((string)(this["JusticeTST4U"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCCSQLTest02\\ccctest8;Initial Catalog=Justice;User Id=EJuser;Password" +
            "=Fh80UXq363PHa4B;Integrated Security=True;TrustServerCertificate=True")]
        public string JusticeTST8U {
            get {
                return ((string)(this["JusticeTST8U"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCCSQLTEST03\\CCCTEST6;Initial Catalog=Justice;Integrated Security=Tru" +
            "e;TrustServerCertificate=True")]
        public string JusticeTEST6 {
            get {
                return ((string)(this["JusticeTEST6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCCSQLTEST02\\cmstest12;Initial Catalog=Justice;Integrated Security=Tr" +
            "ue;TrustServerCertificate=True")]
        public string JusticeTEST12 {
            get {
                return ((string)(this["JusticeTEST12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CMSSQLPRDN03\\ILCOOKPROD;Initial Catalog=Justice;Integrated Security=F" +
            "alse;User ID=ranApp;Password=zRbtrcvxWyQvYj4")]
        public string JusticePRODU {
            get {
                return ((string)(this["JusticePRODU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=cccsqltest03\\cccwebapps;Initial Catalog=CCCAppLog;Integrated Security" +
            "=False;User ID=public2;Password=Public@Access!")]
        public string JusticePRODL {
            get {
                return ((string)(this["JusticePRODL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCCSQLTEST03\\CCCSTAGE02;Initial Catalog=Justice;Integrated Security=T" +
            "rue;TrustServerCertificate=True")]
        public string JusticeSTAGE {
            get {
                return ((string)(this["JusticeSTAGE"]));
            }
        }
    }
}
